Add env Dropdown to Product Version Page
freiheit-com/kuberpult pull request #1185
Opened 2023-12-01 13:49 UTC by gsandok

filtering done based on value in dropdown which is saved in SearchParams

![Screenshot 2023-12-01 at 14 48 08](https://github.com/freiheit-com/kuberpult/assets/47796934/7e965c65-e601-45a2-8d10-f6192bbb4e43)

2023-12-04 10:15 UTC, sven-urbanski-freiheit-com requested changes
.

2023-12-04 12:16 UTC, gsandok commented on services/frontend-service/src/ui/components/EnvironmentCard/EnvironmentCard.tsx
> +    to: string,
updated to using the string !

2023-12-05 15:57 UTC, sven-urbanski-freiheit-com commented on services/frontend-service/src/ui/components/ProductVersion/ProductVersion.test.tsx
> +    },
is the second element here used at all? If not, remove it please.

2023-12-05 15:58 UTC, sven-urbanski-freiheit-com commented on services/frontend-service/src/ui/components/ProductVersion/ProductVersion.tsx
> +    }
nitpick: It would be nice to extract this into a seperate hook function, e.g. `useEnvironmentGroupCombinations"

2023-12-05 16:03 UTC, sven-urbanski-freiheit-com commented on services/frontend-service/src/ui/utils/Links.tsx
> +    const addParam = currentLink.split('?');
please restructure this.
E.g use a function similar to this one https://stackoverflow.com/questions/1714786/query-string-encoding-of-a-javascript-object
1) create object with desired query keys and values
2) call function
3) add result to the link.

2023-12-06 11:58 UTC, sven-urbanski-freiheit-com approved these changes

2023-12-06 12:26 UTC, merged