feat: backend implementation of previous and next buttons on commit info page
freiheit-com/kuberpult pull request #1435
Opened 2024-03-14 17:26 UTC by miguel-crespo-fdc

2024-03-15 10:23 UTC, sven-urbanski-freiheit-com commented on infrastructure/scripts/create-testdata/create-release.sh
> +  --form-string "next_commit_id=${next}" \
the next commit most likely does not exist yet when `create-release.sh` is called.
```suggestion
```

2024-03-15 10:26 UTC, sven-urbanski-freiheit-com commented on services/frontend-service/pkg/handler/release.go
> +	}
```suggestion
```

2024-03-15 10:26 UTC, sven-urbanski-freiheit-com requested changes
(see other comments)

2024-03-15 10:28 UTC, sven-urbanski-freiheit-com commented on infrastructure/scripts/create-testdata/create-release.sh
regarding the PR description:
I assume the backend PR comes before the frontend PR. Therefore, I would remove the screenshot from the backend PR description.

2024-03-15 11:46 UTC, miguel-crespo-fdc commented on services/frontend-service/pkg/handler/release.go
> +	}
Addressed :)

2024-03-15 15:20 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/transformer.go
> +			logger.FromContext(ctx).Sugar().Warnf("commit ID is not a valid SHA1 hash, should be exactly 40 characters [0-9a-fA-F] %s\n", commit)
I would add "source/previous/next" to the error message

2024-03-15 15:22 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/transformer_test.go
> +			//t.Parallel()
```suggestion
			t.Parallel()
```

2024-03-15 15:24 UTC, sven-urbanski-freiheit-com commented on services/frontend-service/pkg/handler/release.go
> +		if len(previousCommitId) == 1 && isCommitId(previousCommitId[0]) {
for the new params: return an error if there are multiple form values.

2024-03-18 13:17 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/transformer_test.go
> +		ExpectedError   string
expected error should be an `error`, not a `string`, see https://github.com/freiheit-com/kuberpult/pull/1433/files

2024-03-18 13:17 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/transformer_test.go
> +			}
this can be simplified with one comparison, see https://github.com/freiheit-com/kuberpult/pull/1433/files (Readme_developers)

2024-03-18 16:26 UTC, sven-urbanski-freiheit-com approved these changes

2024-03-20 11:42 UTC, merged