wip: mc automated migrations
freiheit-com/kuberpult pull request #1598
Opened 2024-05-15 09:54 UTC by miguel-crespo-fdc

2024-05-15 15:55 UTC, sven-urbanski-freiheit-com commented on charts/kuberpult/values.yaml
> +generateMigrations: false
I don't think this flag is necessary. We should just always generate the migrations.

2024-05-15 15:56 UTC, sven-urbanski-freiheit-com requested changes
.

2024-05-15 17:36 UTC, miguel-crespo-fdc commented on Earthfile
> +    COPY cd_database/ cd_database/
See https://github.com/freiheit-com/kuberpult/pull/1602/

2024-05-16 07:38 UTC, sven-urbanski-freiheit-com approved these changes

2024-05-16 08:10 UTC, merged