Mc db undeploy
freiheit-com/kuberpult pull request #1781
Opened 2024-07-19 09:08 UTC by miguel-crespo-fdc

2024-07-19 09:14 UTC, miguel-crespo-fdc commented on pkg/db/overview.go
> +	}
Queued deployment might be nil

2024-07-19 09:15 UTC, miguel-crespo-fdc commented on services/cd-service/pkg/repository/transformer.go
>  		return uint64(releases.Metadata.Releases[l-1]), nil
Guard against empty releases (there was no guard for l = 0)

2024-07-19 09:17 UTC, miguel-crespo-fdc commented on services/cd-service/pkg/repository/transformer.go
>  		if err != nil {
DBSelectAnyRelease Did not make any sense here? Any release simply checks for existence of any release for any app on any env, and we then make decisions based on the result, which cause problems with previously deleted applications

2024-07-19 12:30 UTC, miguel-crespo-fdc commented on services/cd-service/pkg/repository/transformer.go
>  		if err != nil {
And I don't know how it didn't come up earlier

2024-07-19 13:18 UTC, sven-urbanski-freiheit-com commented on pkg/db/db.go
> +	}
please use `CloseRows(row)` instead

2024-07-19 13:19 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/repository.go
> +	if s.DBHandler.ShouldUseOtherTables() && transaction != nil {
```suggestion
	if s.DBHandler.ShouldUseOtherTables() {
```

2024-07-19 13:19 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/repository.go
> +	if s.DBHandler.ShouldUseOtherTables() && transaction != nil {
I don't think we need this extra check.

2024-07-19 13:25 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/transformer.go
> +					return "", fmt.Errorf("UndeployApplication(db): error cannot un-deploy application '%v' the release '%v' is not un-deployed", u.Application, env)
```suggestion
					return "", fmt.Errorf("UndeployApplication(db): error cannot un-deploy application '%v' the current release '%v' is not un-deployed", u.Application, env)
```

2024-07-19 13:28 UTC, sven-urbanski-freiheit-com commented on services/manifest-repo-export-service/pkg/cmd/server.go
>  		logger.FromContext(ctx).Sugar().Warnf("Found an unknown event %s. No further events will be processed.", eslEventType)
I think this was the last transformer to be migrated, right?
In that case, the `default` block here should return an error and not just log a warning.

2024-07-19 13:28 UTC, sven-urbanski-freiheit-com commented on services/manifest-repo-export-service/pkg/repository/repository.go
> +				//TODO(HVG): decide what to do with bad named releases
let's just log this as a warning or error, instead of leaving the TODO in.

2024-07-19 13:30 UTC, sven-urbanski-freiheit-com requested changes
see comments about DBSelectReleasesByApp and default in export-service

2024-07-23 08:44 UTC, sven-urbanski-freiheit-com commented on services/manifest-repo-export-service/pkg/cmd/server.go
> +	return nil, nil
```suggestion
	return nil, fmt.Errorf("Could not find transformer for event type %v", eslEventType)
```

2024-07-23 08:45 UTC, sven-urbanski-freiheit-com approved these changes

2024-07-23 09:47 UTC, merged