chore(cd): add all locks' message, id, author, timestamp to the progosis endpoints
freiheit-com/kuberpult pull request #1958
Opened 2024-09-17 13:27 UTC by AminSlk

Ref: SRX-7CBX2O

2024-09-17 16:54 UTC, miguel-crespo-fdc requested changes

2024-09-17 16:54 UTC, miguel-crespo-fdc commented on services/cd-service/pkg/repository/transformer.go
> +				sortedKeys := sorting.SortKeys(appLocks)
```suggestion
				sortedKeys := sorting.SortKeys(teamLocks)
```

2024-09-17 16:54 UTC, miguel-crespo-fdc commented on services/cd-service/pkg/repository/transformer.go
> +						CreatedAt: timestamppb.New(envLocks[lockId].CreatedAt),
this should be team locks 
```suggestion
						CreatedAt: timestamppb.New(team[lockId].CreatedAt),
```

2024-09-17 16:54 UTC, miguel-crespo-fdc commented on services/cd-service/pkg/repository/transformer.go
> +					CreatedAt: timestamppb.New(envLocks[lockId].CreatedAt),
```suggestion
					CreatedAt: timestamppb.New(appLocks[lockId].CreatedAt),
```

2024-09-18 08:45 UTC, AminSlk commented on services/cd-service/pkg/repository/transformer.go
> +				sortedKeys := sorting.SortKeys(appLocks)
Done

2024-09-18 08:45 UTC, AminSlk commented on services/cd-service/pkg/repository/transformer.go
> +					CreatedAt: timestamppb.New(envLocks[lockId].CreatedAt),
Done

2024-09-18 08:46 UTC, AminSlk commented on services/cd-service/pkg/repository/transformer.go
> +						CreatedAt: timestamppb.New(envLocks[lockId].CreatedAt),
Done

2024-09-18 09:32 UTC, miguel-crespo-fdc approved these changes

2024-09-18 09:38 UTC, merged