undeploy endpoint with tests SRX-M5GOA4
freiheit-com/kuberpult pull request #71
Opened 2022-01-21 16:37 UTC by medo-freiheit

There are two checks before undeploy an application:
1) check locks ( ignore env locks )
2) check that all releases are un-deployed

After testing I figured out that the first check is useless because no matter what is the type of lock the release will not be un-deployed when calling 'prepareUndeploy' endpoint then the 2nd check will fall immediately so the 2nd check contains the 1st one. ( see test number 4 ).

But I kept the 1st check, for now.

2022-01-21 16:55 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/transformer.go
> +			return "", fmt.Errorf("UndeployApplication: error cannot un-deploy application '%v' unlock the application lock in the '%v' release first", u.Application, env)
```suggestion
			return "", fmt.Errorf("UndeployApplication: error cannot un-deploy application '%v' unlock the application lock in the '%v' environment first", u.Application, env)
```

2022-01-21 16:58 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/transformer_test.go
> +			Name: "Undeploy application where there is an application locks shouldn't work",
```suggestion
			Name: "Undeploy application where there is an application lock, shouldn't work",
```

2022-01-21 17:04 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/transformer_test.go
> +func TestUndeployApplicationErrors(t *testing.T) {
I really like the way you tested this!

2022-01-21 17:05 UTC, sven-urbanski-freiheit-com requested changes
.

2022-01-24 09:07 UTC, medo-freiheit commented on services/cd-service/pkg/repository/transformer_test.go
> +				},
Yes! we are still able to add a lock even it's an un-deploy version, Thanks!

2022-01-24 09:08 UTC, medo-freiheit commented on services/cd-service/pkg/repository/transformer_test.go
> +func TestUndeployApplicationErrors(t *testing.T) {
I liked it too 🚀

2022-01-24 10:39 UTC, sven-urbanski-freiheit-com approved these changes

2022-01-24 10:43 UTC, sven-urbanski-freiheit-com commented
Looks good! Please update the commit message before merging. It should be about "what does the endpoint do", e.g something like this:

Added undeploy endpoint to completely remove a service

This endpoint only works when there are no app locks... and ...

2022-01-24 13:03 UTC, merged