DeleteEnvironmentApplication Role Based Access Control
freiheit-com/kuberpult pull request #836
Opened 2023-08-01 17:44 UTC by bernardo-bastos

Implements RBAC on DeleteEnvironmentApplication. Only activated if DEX is enabled.

Rev: DSN-J1WO8X

2023-08-02 09:37 UTC, sven-urbanski-freiheit-com commented on services/cd-service/pkg/repository/transformer.go
> +	err := state.checkUserPermissions(ctx, u.Environment, "*", auth.PermissionDeleteEnvironmentApplication, u.RBACConfig)
```suggestion
	err := state.checkUserPermissions(ctx, u.Environment, c.Application, auth.PermissionDeleteEnvironmentApplication, u.RBACConfig)
```

2023-08-02 09:38 UTC, sven-urbanski-freiheit-com requested changes
.

2023-08-03 12:16 UTC, bernardo-bastos commented on services/cd-service/pkg/repository/transformer.go
> +	err := state.checkUserPermissions(ctx, u.Environment, "*", auth.PermissionDeleteEnvironmentApplication, u.RBACConfig)
Applied the suggest change.

2023-08-03 13:17 UTC, sven-urbanski-freiheit-com approved these changes

2023-08-03 13:27 UTC, merged